# Official Node base image
FROM node

# Author and Maintainer
MAINTAINER Shain Lafazan

# Set Environment
ENV NODE_ENV=production

ADD ./app /app

RUN cd /app && npm i

# Expose ports
EXPOSE 9011

# Run app using PM2
# TODO: PM2
CMD node app/index
